/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package no.uninett.fas.agora.wikinavigator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WikiIndexPage service. Represents a row in the &quot;UN_WikiIndexPage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexPageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexPageImpl}.
 * </p>
 *
 * @author armaz
 * @see WikiIndexPage
 * @see no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexPageImpl
 * @see no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexPageModelImpl
 * @generated
 */
public interface WikiIndexPageModel extends BaseModel<WikiIndexPage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wiki index page model instance should use the {@link WikiIndexPage} interface instead.
	 */

	/**
	 * Returns the primary key of this wiki index page.
	 *
	 * @return the primary key of this wiki index page
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wiki index page.
	 *
	 * @param primaryKey the primary key of this wiki index page
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wiki page ID of this wiki index page.
	 *
	 * @return the wiki page ID of this wiki index page
	 */
	public long getWikiPageId();

	/**
	 * Sets the wiki page ID of this wiki index page.
	 *
	 * @param wikiPageId the wiki page ID of this wiki index page
	 */
	public void setWikiPageId(long wikiPageId);

	/**
	 * Returns the title of this wiki index page.
	 *
	 * @return the title of this wiki index page
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this wiki index page.
	 *
	 * @param title the title of this wiki index page
	 */
	public void setTitle(String title);

	/**
	 * Returns the order of this wiki index page.
	 *
	 * @return the order of this wiki index page
	 */
	public int getOrder();

	/**
	 * Sets the order of this wiki index page.
	 *
	 * @param order the order of this wiki index page
	 */
	public void setOrder(int order);

	/**
	 * Returns the parent ID of this wiki index page.
	 *
	 * @return the parent ID of this wiki index page
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this wiki index page.
	 *
	 * @param parentId the parent ID of this wiki index page
	 */
	public void setParentId(long parentId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WikiIndexPage wikiIndexPage);

	public int hashCode();

	public CacheModel<WikiIndexPage> toCacheModel();

	public WikiIndexPage toEscapedModel();

	public String toString();

	public String toXmlString();
}