/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package no.uninett.fas.agora.wikinavigator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WikiIndex service. Represents a row in the &quot;UN_WikiIndex&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexImpl}.
 * </p>
 *
 * @author armaz
 * @see WikiIndex
 * @see no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexImpl
 * @see no.uninett.fas.agora.wikinavigator.model.impl.WikiIndexModelImpl
 * @generated
 */
public interface WikiIndexModel extends BaseModel<WikiIndex> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wiki index model instance should use the {@link WikiIndex} interface instead.
	 */

	/**
	 * Returns the primary key of this wiki index.
	 *
	 * @return the primary key of this wiki index
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wiki index.
	 *
	 * @param primaryKey the primary key of this wiki index
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the node ID of this wiki index.
	 *
	 * @return the node ID of this wiki index
	 */
	public long getNodeId();

	/**
	 * Sets the node ID of this wiki index.
	 *
	 * @param nodeId the node ID of this wiki index
	 */
	public void setNodeId(long nodeId);

	/**
	 * Returns the content of this wiki index.
	 *
	 * @return the content of this wiki index
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this wiki index.
	 *
	 * @param content the content of this wiki index
	 */
	public void setContent(String content);

	/**
	 * Returns the company ID of this wiki index.
	 *
	 * @return the company ID of this wiki index
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this wiki index.
	 *
	 * @param companyId the company ID of this wiki index
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this wiki index.
	 *
	 * @return the group ID of this wiki index
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this wiki index.
	 *
	 * @param groupId the group ID of this wiki index
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the auto of this wiki index.
	 *
	 * @return the auto of this wiki index
	 */
	public boolean getAuto();

	/**
	 * Returns <code>true</code> if this wiki index is auto.
	 *
	 * @return <code>true</code> if this wiki index is auto; <code>false</code> otherwise
	 */
	public boolean isAuto();

	/**
	 * Sets whether this wiki index is auto.
	 *
	 * @param auto the auto of this wiki index
	 */
	public void setAuto(boolean auto);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WikiIndex wikiIndex);

	public int hashCode();

	public CacheModel<WikiIndex> toCacheModel();

	public WikiIndex toEscapedModel();

	public String toString();

	public String toXmlString();
}