/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package no.uninett.fas.agora.wikinavigator.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import no.uninett.fas.agora.wikinavigator.model.WikiIndexPage;
import no.uninett.fas.agora.wikinavigator.service.WikiIndexLocalService;
import no.uninett.fas.agora.wikinavigator.service.WikiIndexPageLocalService;
import no.uninett.fas.agora.wikinavigator.service.persistence.WikiIndexPagePersistence;
import no.uninett.fas.agora.wikinavigator.service.persistence.WikiIndexPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the wiki index page local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link no.uninett.fas.agora.wikinavigator.service.impl.WikiIndexPageLocalServiceImpl}.
 * </p>
 *
 * @author armaz
 * @see no.uninett.fas.agora.wikinavigator.service.impl.WikiIndexPageLocalServiceImpl
 * @see no.uninett.fas.agora.wikinavigator.service.WikiIndexPageLocalServiceUtil
 * @generated
 */
public abstract class WikiIndexPageLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements WikiIndexPageLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link no.uninett.fas.agora.wikinavigator.service.WikiIndexPageLocalServiceUtil} to access the wiki index page local service.
	 */

	/**
	 * Adds the wiki index page to the database. Also notifies the appropriate model listeners.
	 *
	 * @param wikiIndexPage the wiki index page
	 * @return the wiki index page that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public WikiIndexPage addWikiIndexPage(WikiIndexPage wikiIndexPage)
		throws SystemException {
		wikiIndexPage.setNew(true);

		return wikiIndexPagePersistence.update(wikiIndexPage, false);
	}

	/**
	 * Creates a new wiki index page with the primary key. Does not add the wiki index page to the database.
	 *
	 * @param wikiPageId the primary key for the new wiki index page
	 * @return the new wiki index page
	 */
	public WikiIndexPage createWikiIndexPage(long wikiPageId) {
		return wikiIndexPagePersistence.create(wikiPageId);
	}

	/**
	 * Deletes the wiki index page with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param wikiPageId the primary key of the wiki index page
	 * @return the wiki index page that was removed
	 * @throws PortalException if a wiki index page with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public WikiIndexPage deleteWikiIndexPage(long wikiPageId)
		throws PortalException, SystemException {
		return wikiIndexPagePersistence.remove(wikiPageId);
	}

	/**
	 * Deletes the wiki index page from the database. Also notifies the appropriate model listeners.
	 *
	 * @param wikiIndexPage the wiki index page
	 * @return the wiki index page that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public WikiIndexPage deleteWikiIndexPage(WikiIndexPage wikiIndexPage)
		throws SystemException {
		return wikiIndexPagePersistence.remove(wikiIndexPage);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(WikiIndexPage.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return wikiIndexPagePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return wikiIndexPagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return wikiIndexPagePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return wikiIndexPagePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public WikiIndexPage fetchWikiIndexPage(long wikiPageId)
		throws SystemException {
		return wikiIndexPagePersistence.fetchByPrimaryKey(wikiPageId);
	}

	/**
	 * Returns the wiki index page with the primary key.
	 *
	 * @param wikiPageId the primary key of the wiki index page
	 * @return the wiki index page
	 * @throws PortalException if a wiki index page with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public WikiIndexPage getWikiIndexPage(long wikiPageId)
		throws PortalException, SystemException {
		return wikiIndexPagePersistence.findByPrimaryKey(wikiPageId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return wikiIndexPagePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the wiki index pages.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of wiki index pages
	 * @param end the upper bound of the range of wiki index pages (not inclusive)
	 * @return the range of wiki index pages
	 * @throws SystemException if a system exception occurred
	 */
	public List<WikiIndexPage> getWikiIndexPages(int start, int end)
		throws SystemException {
		return wikiIndexPagePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of wiki index pages.
	 *
	 * @return the number of wiki index pages
	 * @throws SystemException if a system exception occurred
	 */
	public int getWikiIndexPagesCount() throws SystemException {
		return wikiIndexPagePersistence.countAll();
	}

	/**
	 * Updates the wiki index page in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param wikiIndexPage the wiki index page
	 * @return the wiki index page that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public WikiIndexPage updateWikiIndexPage(WikiIndexPage wikiIndexPage)
		throws SystemException {
		return updateWikiIndexPage(wikiIndexPage, true);
	}

	/**
	 * Updates the wiki index page in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param wikiIndexPage the wiki index page
	 * @param merge whether to merge the wiki index page with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the wiki index page that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public WikiIndexPage updateWikiIndexPage(WikiIndexPage wikiIndexPage,
		boolean merge) throws SystemException {
		wikiIndexPage.setNew(false);

		return wikiIndexPagePersistence.update(wikiIndexPage, merge);
	}

	/**
	 * Returns the wiki index local service.
	 *
	 * @return the wiki index local service
	 */
	public WikiIndexLocalService getWikiIndexLocalService() {
		return wikiIndexLocalService;
	}

	/**
	 * Sets the wiki index local service.
	 *
	 * @param wikiIndexLocalService the wiki index local service
	 */
	public void setWikiIndexLocalService(
		WikiIndexLocalService wikiIndexLocalService) {
		this.wikiIndexLocalService = wikiIndexLocalService;
	}

	/**
	 * Returns the wiki index persistence.
	 *
	 * @return the wiki index persistence
	 */
	public WikiIndexPersistence getWikiIndexPersistence() {
		return wikiIndexPersistence;
	}

	/**
	 * Sets the wiki index persistence.
	 *
	 * @param wikiIndexPersistence the wiki index persistence
	 */
	public void setWikiIndexPersistence(
		WikiIndexPersistence wikiIndexPersistence) {
		this.wikiIndexPersistence = wikiIndexPersistence;
	}

	/**
	 * Returns the wiki index page local service.
	 *
	 * @return the wiki index page local service
	 */
	public WikiIndexPageLocalService getWikiIndexPageLocalService() {
		return wikiIndexPageLocalService;
	}

	/**
	 * Sets the wiki index page local service.
	 *
	 * @param wikiIndexPageLocalService the wiki index page local service
	 */
	public void setWikiIndexPageLocalService(
		WikiIndexPageLocalService wikiIndexPageLocalService) {
		this.wikiIndexPageLocalService = wikiIndexPageLocalService;
	}

	/**
	 * Returns the wiki index page persistence.
	 *
	 * @return the wiki index page persistence
	 */
	public WikiIndexPagePersistence getWikiIndexPagePersistence() {
		return wikiIndexPagePersistence;
	}

	/**
	 * Sets the wiki index page persistence.
	 *
	 * @param wikiIndexPagePersistence the wiki index page persistence
	 */
	public void setWikiIndexPagePersistence(
		WikiIndexPagePersistence wikiIndexPagePersistence) {
		this.wikiIndexPagePersistence = wikiIndexPagePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("no.uninett.fas.agora.wikinavigator.model.WikiIndexPage",
			wikiIndexPageLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"no.uninett.fas.agora.wikinavigator.model.WikiIndexPage");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return WikiIndexPage.class;
	}

	protected String getModelClassName() {
		return WikiIndexPage.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = wikiIndexPagePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = WikiIndexLocalService.class)
	protected WikiIndexLocalService wikiIndexLocalService;
	@BeanReference(type = WikiIndexPersistence.class)
	protected WikiIndexPersistence wikiIndexPersistence;
	@BeanReference(type = WikiIndexPageLocalService.class)
	protected WikiIndexPageLocalService wikiIndexPageLocalService;
	@BeanReference(type = WikiIndexPagePersistence.class)
	protected WikiIndexPagePersistence wikiIndexPagePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private WikiIndexPageLocalServiceClpInvoker _clpInvoker = new WikiIndexPageLocalServiceClpInvoker();
}